### PR TITLE
Frontend fixing

### PR DESCRIPTION
**Pull request by LanceR321**

### CODE REVIEW

**Comment by ZorgonOmega** [comment]
Well it looks about right

**Comment by LanceR321** [comment]
needs a review

**Review by LanceR321 — COMMENTED** [review]
please review

**Review by SteveA-99 — APPROVED** [review]
Approved changes

**Comment by SteveA-99** [comment]
good job

**Comment by LanceR321** [comment]
something

**Comment by LanceR321** [comment]
done in another branch

**Pull request closed without merging**
